== Dealing with Data
The basic unit of data in OpenDAX is the _Tag_.  A tag is similar to a variable in a programming language.

=== Data Types
Tags can be one of 15 different data types in OpenDax.  These are given in the following table.

.Data Types
[cols="<,<2,^,^,^",options="header",]
|===
|*Name* |*Description* |*Size (bits)* |*Min* |*Max*
|BOOL |Boolean (True/False) |1 |0 |1
|BYTE |Bit String |8 |0 |255
|SINT |Signed Short Integer |8 |-128 |127
|CHAR |Character |8 |-128 |127
|WORD |Bit String |16 |0 |65,535
|INT |Signed Integer |16 |-32,768 |32,767
|UINT |Unsigned Integer |16 |0 |65,535
|DWORD |Bit String |32 |0 |2^32^
|DINT |Double Integer |32 |-2^31^ |2^31^-1
|UDINT |Unsigned Double Integer |32 |0 |2^32^
|REAL |IEC 754 Floating Point |32 | |
|LWORD |Bit String |64 |0 |2^64^
|LINT |Long Integer |64 |-2^63^ |2^63^-1
|ULINT |Unsigned Long Integer |64 |0 |2^64^
|TIME |Unix Timestamp in mSec |64 | |
|LREAL |IEC 754 Double Floating Point |64 | |
|===

The opendax.h header file contains the definitions for these data types.  These definitions are the name of the data type in the above table prefixed with `DAX_`.  So to represent a Boolean data type to the OpenDAX library you would use the definition `DAX_BOOL`.  These definitions are used anytime your module needs to communicate a data type to the OpenDAX library.  For example, when creating a tag the module has to specify the data type.  You could create an INT tag with a call like this...

[source,c]
----
dax_add_tag("MyInt", DAX_INT, 1);
----

This would create a tag in the server with the name _MyInt_ of type INT.  The 1 as the last argument just means a single member.  A larger number would signify an array.

There are also some typedefs in opendax.h that help with declaring variables within you module code.  They are the same as the datatype definitions except they are all lower case.  For example, if you want to declare a variable that will match the `DAX_DINT' data type you would use `dax_dint' typedef.  These make sure that the variable definitions inside your module match the data types of the tags in OpenDAX.  For the above Tag you could create a variable in C with this code...

[source,c]
----
dax_int myInt;
myInt = 13000;
----

Each Tag in OpenDAX can be a single value of any of these base data types or it can be an array of these.

[source,c]
----
dax_add_tag("MyInt", DAX_INT, 10);
----

This code would generate an array of INT's in the Server.  It is important to note that tags can be redefined as long as the data type stays the same.  If you call `dax_add_tag()' again with a count that is higher than the previous call it would increase the size of the array.  If you call it with a count smaller than the previous, it will ignore it and keep the array the same size.  If you change the data type in the second call the function will return an error.

OpenDAX also supports the concept of a _Compound Data Type_.  This is an aggregate data type that is very similar to a structure in C.  Your module can create a new compound data type or it can use ones that are created by other modules.

These are the four functions that we will need to use from the libdax library.

[source,c]
----
dax_cdt *dax_cdt_new(char *name, int *error);

int dax_cdt_member(dax_state *ds, dax_cdt *cdt, char *name,
                   tag_type mem_type, unsigned int count);

int dax_cdt_create(dax_state *ds, dax_cdt *cdt, tag_type *type);

void dax_cdt_free(dax_cdt *cdt);
----

To create a CDT you first have to allocate a CDT object.

The `dax_cdt_new()' allocates, initializes and returns a pointer to a new CDT object.  The `name`' argument is the name that would be given to the CDT.  The `error`' argument is a pointer to an integer that can indicate any errors.  If there is an error the function will return NULL and the integer pointed to `error`' will be set to the error code.  If you are not interested in this error code then you can pass NULL to the function.

Once you have the object you add members to the CDT one at a time.  These members can be of any previously defined data type including other CDTs.  They can also be arrays and even arrays of other CDT's.  We do this with the `dax_cdt_member()`.  The `cdt`' argument is the object that was returned from the `dax_cdt_new()` function.  The `name` argument is the name that we want to give to our member.  The `mem_type`' argument is either one of the 15 base DAX_* datatypes from above or a predefined compound data type.

Once all of the members have been added the module the `dax_cdt_create()` function is used to send the data type definition to the server and actually create the data type.  The `type` argument to `dax_cdt_create()`' will contain the new type identifier of the created compound data type.  This identifier can be used anywhere another data type definition (such as DAX_DINT) could be used.

The `dax_cdt_free()` function simply frees the memory associated with the new data type.  If the
`dax_cdt_crete()` function is used it will free the object so this function is only necessary
when errors happen and the construction of the data type is being aborted.  Do Not try to free
the memory yourself because there are other data structures in the `dax_cdt` object that have to be
freed.  Simply passing the pointer to `free()` for example will result
in a memory leak.  The `dax_cdt' object should
not be reused.  You can reuse the pointer but old object needs to be
freed with `dax_cdt_free()` or `dax_cdt_crete()` first, and then
reallocate a new one with  `dax_cdt_new()`.

Perhaps it's time for an example.  Let's build a CDT that has the following structure...

----
MyCDT
  MyInteger INT
  MyReals   REAL[10]
  MyBools   BOOL[8]
----

The following code would be used ...

[source,c]
----
dax_cdt *dc;
int error;
tag_type type;

dc = dax_new("MyCDT", &error);
if(dc == NULL) {
    printf("Error code returned is %d\n", error);
    //handle error
} else {
    dax_cdt_member(ds, dc, "MyInteger", DAX_INT, 1);
    dax_cdt_member(ds, dc, "MyReals", DAX_REAL, 10);
    dax_cdt_member(ds, dc, "MyBools", DAX_BOOL, 8);

    error = dax_cdt_create(ds, dc, &type);
    if(error) {
        dax_cdt_free(dc);
        printf("Error from dax_cdt_member() is %d\n", error);
	    //handle error
    } else {
        printf("CDT created!  Data Type = 0x%X\n", type);
    }
}
----

This code will build the above CDT.  There is some error checking missing on the return values of \verb|dax_cdt_member()| functions but this is for clarity.  In your code you would want to check these return values.  Also be careful of the error handling so that you don't exit this code before the `dax_cdt_free()` function has been called to free the `dax_cdt` object.


=== Creating Tags
The main function to use for creating tags for OpenDAX is `dax_tag_add()`.  The prototype is given here.

[source,c]
----
int dax_tag_add(dax_state *ds, tag_handle *h, char *name,
                tag_type type, int count)
----

There are three pieces of information that must be passed to this function to create a tag.  First you have to pass a name.  The name is statically allocated so the size of the tag is fixed.  It must be less than `DAX_TAGNAME_SIZE`.  Right now this is set at 32 characters.  It can easily be changed to allow longer tag names or made smaller to conserve memory in smaller systems.  The definition is in _opendax.h_ and once changed you will have to recompile everything.

The rules for naming tags are pretty simple.  The tag must begin an alphabetic character [a-z or A-Z].  The rest of the tag name can contain underscores, letters or numbers.  For example `ThisTag` and `some_tag23` are both valid tag names.  However `23some_tag`' is not a valid tag name.  Hyphens and symbols are not allowed.  Tags that begin with "_" are reserved for the system's use.

The `type` argument, is the data type of the tag.  This can be one of the base data types or a compound data type.

The  last argument, `count`, is the number of items in the tag.  Basically the tag is either a single tag and `count` would be 1 or the tag represents an array and `count` would be something greater than 1.

The `h` pointer argument is a pointer to a handle.  If this pointer is not NULL `dax_tag_add()` will fill it in with the necessary information to identify the tag.  Tag handles are described in detail in the following section.

=== Tag Handles
It would be very inefficient for the server/library to have to work with the strings that represent different tags in this system.  Strings would use a lot of bandwidth and parsing the strings to determine the actual data point would use extra processor power.

To alleviate some of these concerns OpenDAX uses the idea of a _handle_ to identify tags.  They can also be used to identify parts of the tags.  For example, let's say that we have a tag that is an array of 1,000 INT's named `MyInt`.  The handle that identifies the entire array would be different than one that would identify the items from `MyInt[100]` through `MyInt[199]`, and that would be different than any of the 1,000 handles that would identify a single point in the array.

A `tag_handle` is actually a structure that is defined in _opendax.h_.

There are a couple of ways to get a handle assigned.  The first is to pass a pointer to the `dax_tag_add()` function.  `dax_tag_add()` will assign the information necessary to access the entire tag when the tag is created.

[source,c]
----
int dax_tag_handle(dax_state *ds, tag_handle *h,
                   char *str, int count)
----

The `dax_tag_handle()` function is the other way to get a handle.  The arguments to this function are a pointer to the handle that you want to have assigned, a string that represents the tag for which you would like the handle and an integer that represents the number of items you would like assigned to the handle in the case that the tag is an array.

The string passed to `dax_tag_handle()`' can be more than simply the tag name.  It can be a full description of part of a tag.  Suppose we are using the compound data type that we defined earlier.

[source,c]
----
MyCDT
  MyInteger INT
  MyReals   REAL[10]
  MyBools   BOOL[8]
----

Let's say we create a tag that is a 10 item array of this type, named _MyTag_.  We could represent parts of this tag with the following strings ...

[cols="1,1,2",options="header",]
|===
|*str* |*count* |*Handle represents...*
|"MyTag" |1 |the entire tag
|"MyTag[0]" |1 |the entire first element
|"MyTag[0]" |2 |all of the first two elements
|"MyTag[1].MyInteger" |n/a |the MyInteger member of the 2nd element
|"MyTag[1].MyBools" |n/a |the entire MyBools array of the 2nd element
|"MyTag[2].MyReals[1]" |2 |two MyReals starting with the 2nd one
|===

This is the way that tags and parts of tags should be represented within your module as well.  This representation should be pretty familiar to a C programmer.  Square brackets and numbers are used to index the arrays and '.'s are used to dereference parts of a tag that have a compound data type.  Arrays are zero indexed.

If count is zero and the tag or member is an array the entire array will be assigned to the handle.

Here is the definition of the tag\_handle structure.

[source,c]
----
typedef struct tag_handle {
	tag_index index;     /* The Database Index of the Tag */
	uint32_t byte;       /* The byte offset where the data block starts */
	unsigned char bit;   /* The bit offset */
	uint32_t count;      /* The number of items represented by the handle */
	uint32_t size;       /* The total size of the data block in bytes */
	tag_type type;       /* The data type of the block */
} tag_handle;
----

The tagserver is actually pretty dumb when it comes to retrieving data from the tag database.  The
tagserver only needs the index, the byte offset and the number of bytes.  It's really up to the
module to figure out what to do with that data.  The libdax library hides most of this complexity
from the module programmer.

=== Reading and Writing Data

Once you have a handle to the data you can start to read and write that data.  The three functions
that you will use to read and write data are...

[source,c]
----
int dax_read_tag(dax_state *ds, Handle handle, void *data);
int dax_write_tag(dax_state *ds, Handle handle, void *data);
int dax_mask_tag(dax_state *ds, Handle handle, void *data, void *mask);
----

The `dax_read_tag()` function, as its
name suggests is used to read tag data from the server.  The `void *data`' pointer should point to data that is
formatted in the same way that the handle data is.  Usually this simply means that the variables
in you module should be of the same type and size as what is pointed to by
_handle_

The `dax_write_tag()` function and the `dax_mask_tag()` function are both used to write data to the
server.  Again the `data` pointer should point to a data area within your module that is of the same
type and size as the tag that is represented by the `handle`.  The `dax_mask_tag()` function function
adds the ability to only write part of the data.  The `mask` pointer should point to an area of memory
that is the same size as the `data` pointer.  The only `data`' that will be written to the server will
have a '1' set in that bit location in the `mask`' memory area.

It might be important to understand how large tags are read.  If
the size of the request is larger than the maximum number of bytes that
can be read in a single message, the request will be split up.
This causes a race condition because another module could write to the tags
between these messages.  This will likely, not be an issue for the vast
majority of cases, but it is worth knowing.

Writing tags is also split up into multiple messages if needed.  The same
race condition exists here as well.  Also the amount of data that can be
written is slightly less than can be read.  This is due to the fact that
the message header is larger for writes.
Masked writes are half the size of normal writes, since room has to be made
for the mask.

=== Compound Data

See the implementation of the `dax_cdt_iter()` function to see how to deal with compound data.  The
easiest and least efficient way is to get handles to the individual members of the CDT.

The packing of the CDT is also specified and it's pretty simple.  The members
are packed in the same order in which they were added by the `dax_cdt_member()` function .  They
are single byte aligned and BOOLs are packed into bytes.  One BOOL will take
up an entire byte.  Any subsequent BOOL's that are added will occupy that
same byte until there are more than 8 in which case another byte will be
added.  This continues until the first non-BOOL data type.  The first
non-BOOL typed member will occupy the next byte.  For this reason it is more
efficient to put the BOOL members together.  A single BOOL member followed by
an INT then followed by another BOOL will occupy 4 bytes, one for the first
BOOL, two for the INT and then another byte for the second BOOL.  If we put
the two BOOL members first and second, with the INT last, the data type size
will only be 3 bytes, and we still have room for 6 more BOOLs before the size
would grow.

=== Data Handling Example
